### ISSUE TITLE
Error - Pelase help

### ISSUE THREAD

**Issue by mostaruk** [GreenMeteor/humhub-geolocation-module#4]
Hello I am not sure if this module is working or not however this is a perfect module and just what I have been looking for. After installation on Humhub 1.3.15
 When I try to search members using the distance it throws an error. If anyone could point me in the right direction to help resolve this issue that would be amazing! 

I have removed my URL from the error log
Error : 

yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\user\models\User::distance in /public_html/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /public_html/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('distance') #1 /public_html/protected/humhub/modules/user/models/User.php(193): yii\db\BaseActiveRecord->__get('distance') #2 /public_html/protected/modules/geolocation/views/index/members.php(79): humhub\modules\user\models\User->__get('distance') #3 /public_html/protected/vendor/yiisoft/yii2/base/View.php(336): require('/home/u90902450...') #4 /public_html/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/, Array) #5 /public_html/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/..', Array, Object(humhub\modules\geolocation\controllers\IndexController)) #6 /public_html/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('members', Array, Object(humhub\modules\geolocation\controllers\IndexController)) #7 /public_html/protected/modules/geolocation/controllers/IndexController.php(209): yii\base\Controller->render('members', Array) #8 [internal function]: humhub\modules\geolocation\controllers\IndexController->actionMembers() #9 /public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #10 /public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #11 /public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('members', Array) #12 /public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('geolocation/ind...', Array) #13 /public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #14 /public_html/login.php(64): yii\base\Application->run() #15 {main}

I thank you in advance for your time.

**Comment by ArchBlood** [comment]
I'll look into this right now!

**Comment by ArchBlood** [comment]
Just talked to the team, while we rework this module we will be setting this repo into private, this does not mean there will be a fix for this module available as of yet just letting you know, so that future issues such as this does not happen, at this time we suggest disabling then removing the module, if you can't access the module list use the following command in your command console.

```ssh
cd /path/to/humhub/protected
```
then use this command to disable the module

```ssh
php yii module/disable geolocation
```

**Comment by mostaruk** [comment]
Sorry just saw these messages. Thanks for your response. It only seems to happen when you search. I absolutely love this module! It's perfect for what I need. Please can you point me in the direction of what you believe the issue is. I would be happy to I'll try and fix it.

**Comment by ArchBlood** [comment]
At the moment the issue would be some of the module was just thrown together and with how the core has changed much since the development of this module a lot needs to be changed within the module itself.

So we plan on doing a complete refactoring of the module as soon as we can.

**Comment by mostaruk** [comment]
Ah I see so this only works for x version of humhub. Ok well I will follow this closely. I have it installed locally. I'll have a play. Thank you.
